### PR TITLE
Added Two more keywords for `TransactionType` identification

### PR DESCRIPTION
**Pull request by kartikeyvaish**
Added two more keywords
- Deposited
- Deducted

### CODE REVIEW

**Comment by minimal-scouser** [comment]
Can we not have the single-to-double quote changes? 

I have no problem merging this but for that reason.

**Comment by kartikeyvaish** [comment]
Actually, `Prettier` code formatter added double quotes on save. 

Is there any issue with double quotes? Just asking.

**Comment by minimal-scouser** [comment]
No, it's absolutely fine but let's keep this PR only for the intended changes.
I am more than happy if you want to create a seperate PR just for the formatting changes.

**Comment by kartikeyvaish** [comment]
I've removed `single-to-double` quote changes. Just the two keywords that I added are there. 
[Have a look](https://github.com/minimal-scouser/trny/pull/1/commits/c1e637e8a7326b049c4f44a9f4246aa69ac22633)

Also, I'll create a separate PR for Formatting changes.

**Comment by kartikeyvaish** [comment]
Hey, [Syed](@minimal-scouser ), please review this PR.

**Comment by minimal-scouser** [comment]
Done

**Pull request merged**
